language: node_js
node_js:
  - "lts/dubnium"
before_script:
  - export TZ=America/New_York
install:
    - npm ci --prefix client
    - npm ci --prefix server-sqlite
cache:
  directories:
    - client/node_modules
    - server-sqlite/node_modules
script:
  - npm run build --prefix client
  - npm test --prefix client
  - npm run lint --prefix client
  - npm test --prefix server-sqlite
  - npm run lint --prefix server-sqlite
